[package]
name = "_KERNEL_NAME_"
version = "0.1.0"
authors = ["MAURAISIN Mathias <mamaurai@student.42.fr>"]
edition = "2021"

[lib]
name = "_KERNEL_NAME_"
path = "src/main.rs"
crate-type = ["staticlib"]


# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic

