format_strings = true
max_width = 100
brace_style = "AlwaysNextLine"
fn_params_layout = "Vertical"
fn_args_layout = "Vertical"
group_import = "StdExternalCrate"
wrap_comments = true
tab_spaces = 4
struct_field_align_threshold = 100
enum_discrim_align_threshold = 100
short_array_element_width_threshold = 1
