[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "./arch/i386-unknown-none/target/i386-unknown-none.json"

[target.i386-unknown-none]
runner = "./scripts/qemu.sh"

