[target.i686-unknown-linux-gnu]
rustflags = ["-C", "linker=clang"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "arch/i386/target/i386-unknown-none.json"
